version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
    - pandoc
    - graphviz
  jobs:
    pre_build:
      - cp -r notebooks/dataprocessing/ docs/dataprocessing/notebooks/

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .