name: GitHub Pages

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
  
jobs: 
  website-buid-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with: 
          python-version: 3.7
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install ./
      
      - name: Build
        run: make html
        working-directory: ./docs
      
      # github pages creates jekyll build by default, just want to point to index.html
      - name: Disable jekyll builds
        run: touch docs/build/html/.nojekyll
      
      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
