name: GitHub Pages

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
  
jobs: 
  website-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
          
      - name: Setup tools
        run: | 
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install --upgrade pip-tools 
    
      - name: Pip compile
        run: |
          pip-compile requirements.in
          cat requirements.txt
    
      - name: Upload Requirements
        uses: actions/upload-artifact@v2
        with: 
          name: requirements.txt
          path: requirements.txt
    
      - name: Install dependencies
        run: |
          pip-sync requirements.txt
    
      - name: Install package
        run: |
          pip install -v .
          
      - name: Build and Commit
        uses: sphinx-notes/pages@v2
        with:
         documentation_path: ./docs
         requirements_path: ./requirements.txt
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: gh-pages
