name: GitHub Pages

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
  
jobs: 
  website-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
          
      - name: Build and Commit
        uses: sphinx-notes/pages@v2
      - name: Push changes
        uses: ad-m/github-push-action@v2
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: gh-pages
