name: Release raimitigations to Pypi

# trigger manually ("collaborator" or above permissions should be required)
on:
  workflow_dispatch: 
    inputs:
      releaseType:
        type: choice
        description: "Test or Prod PyPi"
        options:
          - Test
          - Prod
        required: true

jobs: 
  release-pypi:
    runs-on: ubuntu-latest
    steps:
       
       # build wheel 
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: update and upgrade pip, setuptools, wheel and twine
        run: |
           python -m pip install --upgrade pip
           pip install --upgrade setuptools wheel twine pip-tools
       
      - name: Pip compile
        run: |
          pip-compile requirements.in
          cat requirements.txt
          pip-sync requirements.txt
           
      - name: Install current package
        run: |
          pip install -v .
       
      - name: build wheel
        run: python setup.py sdist bdist_wheel
         
        # run tests before uploading to PyPi
      - name: run tests
        run: pytest test/databalanceanalysis/.
        
      - name: check release type
        run: |
          echo ${{ github.events.inputs.releaseType }}
          echo ${{ github.events.inputs.releaseType == 'Test'}}
          echo ${{ github.events.inputs.releaseType == 'Prod'}}
        
        # publish to Test or Normal PyPi
      - name: Publish package to Test Pypi
        if: ${{ github.events.inputs.releaseType == 'Test'}}
        uses: pypa/gh-action-pypi-publish@release/v1
        with: 
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
     
      - name: Publish package to Pypi
        if: ${{ github.events.inputs.releaseType == 'Prod'}}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
            
        
       
         
