name: Release raimitigations to Pypi

# trigger manually ("collaborator" or above permissions should be required)
on:
  workflow_dispatch: 
    inputs:
      type:
        description: "Test or Prod PyPi"
        required: true
        deault: "Test"

jobs: 
  release-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: fail if not Test nor Prod
      if: ${{ ! (github.events.inputs.type == 'Test' || github.events.inputs.type == 'Prod') }} 
      run: |
        echo "Only Test or Prod can be used."
        exit 1
       
       # build wheel 
       - uses: actions/checkout@v2
       
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
          python-version: 3.7
          
       - name: update and upgrade pip, setuptools, wheel and twine
         run: |
           python -m pip install --upgrade pip
           pip install --upgrade setuptools wheel twine
       
       - name: install requirements.txt 
         run: |
           pip install -r requirements.txt
       
       - name: build wheel
         run: python setup.py sdist bdist_wheel
         
        # run tests before uploading to PyPi
        - name: run tests
          run: pytest .\test\databalanceanalysis\.
        
        # publish to Test or Normal PyPi
        - name: Publish package to Test Pypi
          if: ${{ github.events.inputs.type == 'Test'}}
          uses: pypa/gh-action-pypi-publish@release/v1
          with: 
            user: __token__
            password: ${{ secrets.TEST_PYPI_TOKEN }}
            repository_url: https://test.pypi.org/legacy/
       
        - name: Publish package to Pypi
          if: ${{ github.events.inputs.type == 'Prod'}}
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_TOKEN }}
            
        
       
         
